### ISSUE TITLE
Request of next release: version 2.0.2

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common_msgs#11]
@k-okada Could you please do this?

**Comment by wkentaro** [comment]
I tried but it was impossible. http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/add_tag/170/console

**Comment by k-okada** [comment]
since we no longer hydro deb build and this version has new service, so I
think we'd better to use 3.0.0

## 

◉ Kei Okada

**Comment by wkentaro** [comment]
I see. So, could you please next major release?

**Comment by wkentaro** [comment]
@k-okada Thank you.
