### ISSUE TITLE
Release jsk_common_msgs into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [jsk-ros-pkg/jsk_common_msgs#25]
Would you mind releasing `jsk_common_msgs` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 13 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by k-okada** [comment]
thanks @sloretz released https://github.com/ros/rosdistro/pull/24696
